[project]
name = "inspector"
version = "0.1.0"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
"a2a-inspector",
"Flask",
"flask_cors",
]

[tool.uv.sources]
a2a-inspector = { workspace = true }